### ISSUE TITLE
DGL for WSOL

### ISSUE THREAD

**Issue by chuangchuangtan** [xiaomengyc/Weakly-Supervised-Object-Localization#2]
I upload the source for DGL
Title: Dual-Gradients Localization Framework for Weakly Supervised Object Localization
Pdf: https://dl.acm.org/doi/10.1145/3394171.3413622
code: https://github.com/chuangchuangtan/DGL

Thank you

**Comment by xiaomengyc** [comment]
Thanks for letting me know!
I have added this paper and the code to the list.
